### ISSUE TITLE
 JULIA: BoundsError when running in Python

### ISSUE THREAD

**Issue by thosvarley** [dpshorten/CoTETE.jl#1] opened 2021-10-12 22:45 UTC
I am testing the CoTETE package in Python and keep running into this odd error:

`IndexError: <PyCall.jlwrap (in a Julia function called from Python)`

`JULIA: BoundsError: attempt to access 4333-element Vector{Float64} at index [0]`

`Stacktrace:`

` [1] getindex(A::Vector{Float64}, i1::Int64)
   @ Base ./array.jl:805`

` [2] make_one_embedding(observation_time_point::Float64, event_time_arrays::Vector{Vector{Float64}}, most_recent_event_indices::Vector{Integer}, embedding_lengths::Vector{Int64})
   @ CoTETE ~/.bin/CoTETE.jl/src/preprocessing.jl:99`
 
`[3] make_embeddings_along_observation_time_points(observation_time_points::Vector{Float64}, start_observation_time_point::Int64, num_observation_time_points_to_use::Int64, event_time_arrays::Vector{Vector{Float64}}, embedding_lengths::Vector{Int64})
   @ CoTETE ~/.bin/CoTETE.jl/src/preprocessing.jl:166`

 `[4] preprocess_event_times(parameters::CoTETE.CoTETEParameters, target_events::Vector{Float64}; source_events::Vector{Float64}, conditioning_events::Vector{Vector{Float32}})
   @ CoTETE ~/.bin/CoTETE.jl/src/preprocessing.jl:452`

` [5] estimate_TE_and_p_value_from_event_times(parameters::CoTETE.CoTETEParameters, target_events::Vector{Float64}, source_events::Vector{Float64}; conditioning_events::Vector{Vector{Float32}}, return_surrogate_TE_values::Bool)
   @ CoTETE ~/.bin/CoTETE.jl/src/CoTETE.jl:363`

` [6] invokelatest(::Any, ::Any, ::Vararg{Any, N} where N; kwargs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:return_surrogate_TE_values,), Tuple{Bool}}})
   @ Base ./essentials.jl:710`

` [7] _pyjlwrap_call(f::Function, args_::Ptr{PyCall.PyObject_struct}, kw_::Ptr{PyCall.PyObject_struct})
   @ PyCall ~/.julia/packages/PyCall/BD546/src/callback.jl:32`

 `[8] pyjlwrap_call(self_::Ptr{PyCall.PyObject_struct}, args_::Ptr{PyCall.PyObject_struct}, kw_::Ptr{PyCall.PyObject_struct})
   @ PyCall ~/.julia/packages/PyCall/BD546/src/callback.jl:44>`

The length of the source and the target numpy arrays are both several thousand timesteps, and they are both float64 type. 

The code runs fine for apparently identical inputs - I can't seem to figure out what is wrong with this particular set of sources and targets.

**Comment by dpshorten** [comment] 2021-10-14 02:48
Hi Thomas,

Firstly, thanks for getting in touch. It's always great to know that the
software is being used. Moreover, being informed of potential bugs is super
useful.

It does sound like you are likely encountering a minor bug of some sort
there. Is it possible for you to send me the data and python script that is
causing this so that I can try recreating it on my end?

Warm Regards

David Shorten

**Comment by thosvarley** [comment] 2021-10-14 13:56
Here you go. You might need to change the paths, but otherwise it should run out of the box - I just confirmed that I'm still getting the error, although it seems particular to the value i=29 (if you change i=28 it will run).  
[spike.mat.gz](https://github.com/dpshorten/CoTETE.jl/files/7346540/spike.mat.gz)
[cotete_example.py.gz](https://github.com/dpshorten/CoTETE.jl/files/7346541/cotete_example.py.gz)

**Comment by dpshorten** [comment] 2022-01-05 07:36
Hi Thomas,

Firstly, I need to apologise for taking so long to get back to you. I feel
pretty bad about this, given that you had taken the time to provide me with
feedback on my software. My thesis submission deadline is in 2 months time,
and I had been falling a bit behind schedule late last year, which (along
with a few other issues) resulted in me panicking a bit and letting
important things like this bug slip by.

I realise that this reply is probably too late to help you with your
research, but I decided that I needed to dig into what might have been
causing the behaviour that you observed, and then decided that I might as
well also let you know what the cause of the issue was.

So, you had indeed found a bug in the code. The specific example which you
were providing had early source and target events with identical timestamps
(an edge case which the software should certainly be able to handle!). This
resulted in the erroneous setting of the first target event to use. This
event has to be sufficiently far forward so that all the history embeddings
can be constructed from it. However, the software's incorrect handling of
the identical timestamps resulted in the first target event not being
advanced far forward enough. I have now fixed this behaviour and the latest
release of the package on GitHub has this fix incorporated.

I must thank you for bringing this to my attention. I don't think that I
would have ever encountered this behaviour myself, but other users might
well have run into it in the future, so being able to catch it early is of
great benefit.

Please don't hesitate to get in touch with any other questions. I promise
that the next time around I will try and make up for this super slow
response with a much quicker one!!

Warm Regards
David Shorten

**Comment by dpshorten** [comment] 2022-01-09 06:07
This has been fixed in v0.2.1. There was a small bug in the way the first target event was being chosen, which caused an issue when source and target events with identical timestamps were present, as in the example you provided.

Thanks for bringing this to my attention!!

**Closed as completed by dpshorten** 2022-01-09 06:07 UTC
